language: rust
sudo: false
addons:
    apt:
        packages:
          - libssl-dev
matrix:
  include:
    - rust: rust:
        - stable
        - nightly
      install:
        - npm i
      cache:
        - directories:
          - node_modules
          - /home/travis/.cargo
          - moz-central
      before_cache:
        - rm -rf /home/travis/.cargo/registry
      script:
        - cargo test --features moz_central
      after_script:
      stages:
        after_script:
          - if branch in (master, next)
      after_success: |
        if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
          RUSTFLAGS="--cfg procmacro2_semver_exempt" cargo +nightly install cargo-tarpaulin &&
          cargo +nightly tarpaulin --no-count --skip-clean --out Xml &&
          bash <(curl -s https://codecov.io/bash)
        fi
notifications:
  email: never
