language: rust
sudo: false
addons:
    apt:
        packages:
          - libssl-dev
rust:
  - stable
  - nightly
install:
  - npm i
cache:
  - directories:
    - node_modules
    - /home/travis/.cargo
    - moz-central
before_cache:
  - rm -rf /home/travis/.cargo/registry
  # - |
    if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
      bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    fi
script:
  - cargo test --features moz_central
after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --out Xml &&
    bash <(curl -s https://codecov.io/bash)
  fi
matrix:
  allow_failures:
    - rust: nightly
notifications:
  email: never
