language: rust
sudo: false
matrix:
  include:
    - rust: stable
      install:
        - npm i
      cache:
        - directories:
          - node_modules
          - /home/travis/.cargo
      before_cache:
        - rm -rf /home/travis/.cargo/registry
      script:
        - cargo test
        - cargo +beta test
      after_script:
      stages:
        after_script:
          - if branch in (master, next)
notifications:
  email: never