[package]
name = "resp"
version = "0.1.0"
authors = ["Robert Masen <r@robertmasen.pizza>"]
repository = "https://github.com/FreeMasen/RESP"


[dependencies]
ress = "0.4"
log = "0.4.4"
env_logger = "0.5.13"

[features]
major_libs = []
