[package]
name = "ressa"
version = "0.2.2"
authors = ["Robert Masen <r@robertmasen.pizza>"]
repository = "https://github.com/FreeMasen/RESP"
description = "An ECMAscript parser"
license = "MIT"
readme = "./README.md"
keywords = ["JavaScript", "parsing", "JS", "ES", "ECMA"]
categories = ["parsing", "text-processing", "web-programming"]

[dependencies]
ress = "0.5.1"
log = "0.4.5"
env_logger = "0.5.13"
backtrace = "0"

[features]
major_libs = []

[dev-dependencies]
term-painter = "0.2.4"
docopt = "1"
walkdir = "2"
serde_derive = "1"
serde = "1"